<?php
	$this->headTitle('User manager');
	
	$form = $this->userForm;
	$form->setAttribute('action', $this->url('admin/user-list'));
	$form->prepare();

	//$this->form()->openTag($form);
	//$this->formHidden($form->get('id'));
	//$this->formRow($form->get('title'));
	//$this->formRow($form->get('artist'));
	//$this->formSubmit($form->get('submit'));
	//$this->form()->closeTag();
	
?>
<div style="width:100%">
	<?=$this->form()->openTag($form)?>
	<fieldset>
		<legend>Filters</legend>
		<div class="center" style="width:500px">
			<div class="control-group">
				<div class="controls">
					<div class="row">
						<div class="span5">
							<?=$this->formRow($form->get('email'))?>
						</div>
						<div class="span5">
							<?=$this->formRow($form->get('username'))?>
						</div>
					</div>
				</div>
				<div class="controls">
					<div class="row">
						<div class="span5">
							<?=$this->formRow($form->get('firstName'))?>
						</div>
						<div class="span5">
							<?=$this->formRow($form->get('lastName'))?>
						</div>
					</div>
				</div>
				<div class="controls offset2">
					<div class="row">
						<div class="span5">
							<?=$this->formRow($form->get('send'))?>
						</div>
						<div class="span5">
							<?=$this->formButton($form->get('clear'))?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</fieldset>
	<?=$this->form()->closeTag($form)?>
</div>