<?php
	namespace Application\Model\Repository;

	use 
		Application\Utility\Cache,
		Doctrine\ORM\EntityRepository;

	/**
	 * Role
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class Role extends EntityRepository
	{
		/**
		 * @return Array
		 */
		public function getList()
		{
			$query = $this->createQueryBuilder('r')->getQuery();
			
			Cache::setCacheForQuery($query, array(
				'meta'		=> $this->getClassMetadata(), 
				'method'	=> __FUNCTION__
			));
			
			return $query->getResult();
		}
	}
