<?php

namespace Application\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Artist
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Artist extends EntityRepository
{
}
