<?php
	namespace Application\Model\Repository;

	use 
		Application\Utility\Cache,
		DoctrineModule\Authentication\Adapter\ObjectRepository,
		Doctrine\ORM\Query\Expr,
		Doctrine\ORM\EntityRepository;

	/**
	 * SystemUser
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	final class SystemUser extends EntityRepository
	{
		/**
		 * @param Integer $id
		 * @return Application\Model\Entity\SystemUser
		 */
		public function findById($id)
		{
			$qb = $this->makeSelectQuery();
			
			$query = 
				$qb->
					where('u.id = :id')->
					setParameter(':id', $id)->
					getQuery();
			
			Cache::setCacheForQuery(
				$query, 
				array(
					'meta' => $this->getClassMetadata(), 
					'method' => __FUNCTION__, 
					'args' => array($id)
				)
			);
			
			return $query->getOneOrNullResult();
		}
		
		/**
		 * @param String $email
		 * @return Application\Model\Entity\SystemUser
		 */
		public function findByEmail($email)
		{
			$qb = $this->makeSelectQuery();
			
			$query =
				$qb->
					where('u.email = :email')->
					setParameter(':email', $email)->
					getQuery();
			
			Cache::setCacheForQuery(
				$query, 
				array(
					'meta'		=> $this->getClassMetadata(), 
					'method'	=> __FUNCTION__, 
					'args'		=> array($email)
				)
			);
			
			return $query->getOneOrNullResult();
		}
		
		/**
		 * @return Doctrine\ORM\Query
		 */
		private function makeSelectQuery()
		{
			return
				$this->
					_em->
						createQueryBuilder()->
							select(array('u', 'r'))->
							from($this->getEntityName(), 'u')->
							leftJoin('u.roles', 'r');
		}
	}