<?php
	namespace Application\Model\Repository;

	use 
		DoctrineModule\Authentication\Adapter\ObjectRepository,
		Doctrine\ORM\EntityRepository;

	/**
	 * SystemUser
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class SystemUser extends EntityRepository
	{
		
	}
