<?php
	$title = 'Login';
	$this->headTitle($title);
?>

<div class="center" style='width:400px'>
	<fieldset>
		<legend><?php echo $this->escapeHtml($title); ?></legend>
		<?php if ($result === false):?>
		<div class="error">Wrong password or email</div>
		<?php endif;?>
<?php

	$form = $this->loginForm;
	$form->setAttribute('action', $this->url('admin/default', array('controller' => 'auth', 'action' => 'login')));
	$form->prepare();
	
	$formLabel = $this->plugin('formLabel');
?>	
		<?=$this->form()->openTag($form) . PHP_EOL?>
		
		<?=$formLabel->openTag()?><?=$form->get('email')->getOption('label')?>
		<?=$this->formEmail($form->get('email')) . PHP_EOL?>
		<?=$formLabel->closeTag()?>
		
		<?=$formLabel->openTag()?><?=$form->get('password')->getOption('label')?>
		<?=$this->formPassword($form->get('password')) . PHP_EOL?>
		<?=$formLabel->closeTag()?>
		<br/><br/>
		<?=$this->formInput($form->get('send')) . PHP_EOL?>
		<?=$this->form()->closeTag($form) . PHP_EOL?>
	</fieldset>
</div>