<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Zaptv Portal Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin.css')?>

        <!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/tiny_mce/jquery.tinymce.js')
							  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
							  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
							  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

		<script type="text/javascript">
			$().ready(function() {
				$('textarea.tinymce').tinymce({
					// Location of TinyMCE script
					script_url : '/../js/tiny_mce/tiny_mce.js',
					
					height : "480",
					
					// General options
					theme : "advanced",
					plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",

					// Theme options
					theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
					theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
					theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
					theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
					theme_advanced_toolbar_location : "top",
					theme_advanced_toolbar_align : "left",
					theme_advanced_statusbar_location : "bottom",
					theme_advanced_resizing : true,

					// Example content CSS (should be your site CSS)
					//content_css : "css/content.css",

					// Drop lists for link/image/media/template dialogs
					template_external_list_url : "lists/template_list.js",
					external_link_list_url : "lists/link_list.js",
					external_image_list_url : "lists/image_list.js",
					media_external_list_url : "lists/media_list.js",

					// Replace values for the template plugin
					template_replace_values : {
						username : "Some User",
						staffid : "991234"
					}
				});
			});
		</script>
	</head>
    <body id="body">
        <div class="container">
            <div id="header"  class="textCenter">
				<h2>Admin area</h2>
			</div>
			<div class="clear"></div>
			<div class="center" style="width:1200px">
				<div class="left" id="leftColumn">
					<fieldset>
						<legend>Menu</legend>
						<?= $this->navigation('navigation')->menu(); ?>
					</fieldset>
				</div>
				<div class="left" id="rightColumn">
					<?php echo $this->content; ?>
				</div>
				<div class="clear"></div>
				<div id="footer" class="textCenter">
					<h2>Admin Footer</h2>
				</div>
			</div>
			<div class="clear"></div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
