<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Zaptv Portal Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->muneeHeadLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>

        <!-- Scripts -->
		<?php echo $this->muneeHeadScript()
						->prependFile($this->basePath() . '/js/libs/jquery/plugins/bootstrap.min.js')
						->prependFile($this->basePath() . '/js/libs/jquery/min.js') ?>
	</head>
    <body id="body">
        <div class="container">
			<!-- Header -->
			<div class="container-fluid no-padding header">
				<div class="row-fluid fill-height">
					<div class="page-header">
						<h1>Admin Area</h1>
					</div>
				</div>
			</div>
			<!-- Content Wrapper -->
			<div class="container-fluid no-padding fill">
				<div class="row-fluid">
					<div class="span2">
						<div class="well sidebar-nav-fixed no-padding">
							<?=$this->navigation('admin_navigation')->menu()->renderMenu(null, array('ulClass' => 'nav nav-list'))?>
						</div>
					</div>
					<div class="span10">
						<p class="center-text"><?=$this->content?></p>
					</div>
				</div>
			</div>
			<!-- Footer -->
			<div id="footer">
				<div class="container-fluid">
					<p>&COPY;2005 - 2013 by Noussoft Ltd. All rights reserved.</p>
				</div>
			</div>
		</div>
		<?php echo $this->inlineScript() ?>
    </body>
</html>
