<?php
	$title = 'Add news';
	$this->headTitle($title);
?>

<div class="center" style='width:400px'>
	<fieldset>
		<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php

	$form = $this->newsForm;

	$form->setAttribute(
		'action', 
		$this->url(
			'admin/default', array('controller' => 'news', 'action' => 'add')
		)
	);
	
	$form->prepare();
?>
	<?=$this->form()->openTag($form) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('title')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('body')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('keywords')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('publish_date')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('headline')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('type')) . PHP_EOL?><br/><br/>
	<?=$this->formRow($form->get('send')) . PHP_EOL?><br/><br/>
	<?=$this->form()->closeTag($form) . PHP_EOL?><br/><br/>
	</fieldset>
</div>